<?php

namespace Database\Seeders;

use App\Models\Client;
use App\Models\User;
use Illuminate\Database\Seeder;

class ClientSeeder extends Seeder
{
    public function run(?User $admin = null): void
    {
        $admin ??= User::where('email', 'admin@contabo.test')->firstOrFail();

        $clients = [
            [
                'person_type' => 'moral',
                'name' => 'Constructora Norteña SA de CV',
                'tax_id' => 'CNO920315AB1',
                'tax_regime' => '601',
                'curp' => null,
                'legal_rep_name' => 'Roberto Garza Treviño',
                'legal_rep_rfc' => 'GATR750820HNL',
                'economic_activity' => 'Construcción de obras de ingeniería civil',
                'scian_code' => '23711',
                'employee_count' => 85,
                'email' => 'contabilidad@constructoranortena.com.mx',
                'phone' => null,
                'address' => 'Av. Constitución 1450 Col. Centro',
                'city' => 'Monterrey',
                'state' => 'Nuevo León',
                'country' => 'MX',
                'postal_code' => '64000',
                'status' => 'active',
                'billing_cycle' => 'monthly',
                'obligations_periodicity' => 'mensual',
                'compliance_level' => 'high',
                'relationship_started_at' => '2021-03-01',
                'onboarding_completed_at' => '2021-03-15 10:00:00',
                'onboarding_notes' => 'Cliente referido por notaría. Documentación completa desde el inicio.',
                'portal_sat_user' => 'cnortena_sat',
                'portal_sat_password' => 'S@t2021Cnrt!',
                'documents' => [
                    'constancia_situacion_fiscal' => true,
                    'poder_notarial' => true,
                    'identificacion' => true,
                ],
            ],
            [
                'person_type' => 'fisica',
                'name' => 'Ana Lucía Mendoza Ríos',
                'tax_id' => 'MERA850610KP3',
                'tax_regime' => '612',
                'curp' => 'MERA850610MDFNNS04',
                'legal_rep_name' => null,
                'legal_rep_rfc' => null,
                'economic_activity' => 'Comercio al por menor de ropa y accesorios',
                'scian_code' => '46411',
                'employee_count' => 4,
                'email' => 'analucia.mendoza@gmail.com',
                'phone' => null,
                'address' => 'Calle Morelos 220 Col. Independencia',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'country' => 'MX',
                'postal_code' => '44340',
                'status' => 'active',
                'billing_cycle' => 'monthly',
                'obligations_periodicity' => 'bimestral',
                'compliance_level' => 'medium',
                'relationship_started_at' => '2022-07-15',
                'onboarding_completed_at' => '2022-07-20 09:30:00',
                'onboarding_notes' => 'Negocio familiar. Llevan su contabilidad en cuaderno; se migró a sistema en alta.',
                'portal_sat_user' => 'amenrio85',
                'portal_sat_password' => 'Jalisco#85!',
                'documents' => [
                    'constancia_situacion_fiscal' => true,
                    'poder_notarial' => false,
                    'identificacion' => true,
                ],
            ],
            [
                'person_type' => 'moral',
                'name' => 'Distribuidora Alimentaria del Bajío SC de RL',
                'tax_id' => 'DAB991201JK7',
                'tax_regime' => '601',
                'curp' => null,
                'legal_rep_name' => 'Carmen Villanueva Soto',
                'legal_rep_rfc' => 'VISC700412MDF',
                'economic_activity' => 'Distribución de alimentos y bebidas al mayoreo',
                'scian_code' => '43191',
                'employee_count' => 32,
                'email' => 'admin@dabalimento.com.mx',
                'phone' => null,
                'address' => 'Blvd. Díaz Ordaz 3800 Parque Industrial',
                'city' => 'León',
                'state' => 'Guanajuato',
                'country' => 'MX',
                'postal_code' => '37490',
                'status' => 'active',
                'billing_cycle' => 'monthly',
                'obligations_periodicity' => 'mensual',
                'compliance_level' => 'high',
                'relationship_started_at' => '2020-01-10',
                'onboarding_completed_at' => '2020-01-25 11:00:00',
                'onboarding_notes' => 'Cliente antiguo con historial limpio ante el SAT.',
                'portal_sat_user' => 'dab_fiscal99',
                'portal_sat_password' => 'F1sc@lB4ji0!',
                'documents' => [
                    'constancia_situacion_fiscal' => true,
                    'poder_notarial' => true,
                    'identificacion' => true,
                ],
            ],
            [
                'person_type' => 'fisica',
                'name' => 'Jorge Iván Castellanos Medina',
                'tax_id' => 'CAMJ780904ER5',
                'tax_regime' => '606',
                'curp' => 'CAMJ780904HDFSTV08',
                'legal_rep_name' => null,
                'legal_rep_rfc' => null,
                'economic_activity' => 'Arrendamiento de locales comerciales y bodegas',
                'scian_code' => '53119',
                'employee_count' => 1,
                'email' => 'jcastellanos.rentas@outlook.com',
                'phone' => null,
                'address' => 'Privada Laureles 18 Col. Las Águilas',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'country' => 'MX',
                'postal_code' => '01710',
                'status' => 'active',
                'billing_cycle' => 'monthly',
                'obligations_periodicity' => 'mensual',
                'compliance_level' => 'medium',
                'relationship_started_at' => '2023-02-01',
                'onboarding_completed_at' => '2023-02-10 08:00:00',
                'onboarding_notes' => 'Propietario de 6 locales. Emite CFDI de arrendamiento mensual.',
                'portal_sat_user' => 'jcastellanos78',
                'portal_sat_password' => 'Arr3nd@2023!',
                'documents' => [
                    'constancia_situacion_fiscal' => true,
                    'poder_notarial' => false,
                    'identificacion' => true,
                ],
            ],
            [
                'person_type' => 'moral',
                'name' => 'TechSoluciones del Norte SA de CV',
                'tax_id' => 'TSN180720PQ2',
                'tax_regime' => '601',
                'curp' => null,
                'legal_rep_name' => 'Miguel Ángel Flores Rojas',
                'legal_rep_rfc' => 'FORM900315HNL',
                'economic_activity' => 'Desarrollo de software y consultoría TI',
                'scian_code' => '54151',
                'employee_count' => 18,
                'email' => 'finanzas@techsoluciones.mx',
                'phone' => null,
                'address' => 'Paseo de los Leones 450 Col. Cumbres',
                'city' => 'Monterrey',
                'state' => 'Nuevo León',
                'country' => 'MX',
                'postal_code' => '64610',
                'status' => 'active',
                'billing_cycle' => 'monthly',
                'obligations_periodicity' => 'mensual',
                'compliance_level' => 'high',
                'relationship_started_at' => '2019-08-01',
                'onboarding_completed_at' => '2019-08-20 14:00:00',
                'onboarding_notes' => 'Empresa exportadora de servicios. Aplica tasa 0% IVA en facturación al extranjero.',
                'portal_sat_user' => 'techsol_fiscal18',
                'portal_sat_password' => 'T3chS@t2019!',
                'documents' => [
                    'constancia_situacion_fiscal' => true,
                    'poder_notarial' => true,
                    'identificacion' => true,
                ],
            ],
            [
                'person_type' => 'fisica',
                'name' => 'Patricia Elena Ruiz Hernández',
                'tax_id' => 'RUHP930215FN8',
                'tax_regime' => '625',
                'curp' => 'RUHP930215MDFRZV01',
                'legal_rep_name' => null,
                'legal_rep_rfc' => null,
                'economic_activity' => 'Venta de productos a través de plataformas digitales',
                'scian_code' => '46591',
                'employee_count' => 2,
                'email' => 'patricia.ruiz.shop@gmail.com',
                'phone' => null,
                'address' => 'Calle Tulipán 55 Col. Jardines del Bosque',
                'city' => 'Zapopan',
                'state' => 'Jalisco',
                'country' => 'MX',
                'postal_code' => '45010',
                'status' => 'onboarding',
                'billing_cycle' => 'monthly',
                'obligations_periodicity' => 'bimestral',
                'compliance_level' => 'medium',
                'relationship_started_at' => '2024-11-01',
                'onboarding_completed_at' => null,
                'onboarding_notes' => 'Vendedora en Mercado Libre y Amazon. En proceso de alta; pendiente constancia actualizada.',
                'portal_sat_user' => null,
                'portal_sat_password' => null,
                'documents' => [
                    'constancia_situacion_fiscal' => false,
                    'poder_notarial' => false,
                    'identificacion' => true,
                ],
            ],
            [
                'person_type' => 'moral',
                'name' => 'Agropecuaria Los Mezquites SPR de RI',
                'tax_id' => 'ALM050610DE4',
                'tax_regime' => '601',
                'curp' => null,
                'legal_rep_name' => 'Ernesto Salinas Vázquez',
                'legal_rep_rfc' => 'SAVE680901HZA',
                'economic_activity' => 'Producción de granos y cereales',
                'scian_code' => '11111',
                'employee_count' => 12,
                'email' => 'contabilidad@losmezquites.com.mx',
                'phone' => null,
                'address' => 'Carretera Zacatecas-Fresnillo Km 14',
                'city' => 'Fresnillo',
                'state' => 'Zacatecas',
                'country' => 'MX',
                'postal_code' => '99010',
                'status' => 'active',
                'billing_cycle' => 'quarterly',
                'obligations_periodicity' => 'mensual',
                'compliance_level' => 'medium',
                'relationship_started_at' => '2018-05-01',
                'onboarding_completed_at' => '2018-05-20 09:00:00',
                'onboarding_notes' => 'Sociedad de producción rural. Cuenta con beneficios fiscales agropecuarios.',
                'portal_sat_user' => 'mezquites_agro05',
                'portal_sat_password' => 'Agr0Z@c2018!',
                'documents' => [
                    'constancia_situacion_fiscal' => true,
                    'poder_notarial' => true,
                    'identificacion' => false,
                ],
            ],
            [
                'person_type' => 'fisica',
                'name' => 'Luis Fernando Chávez Ortega',
                'tax_id' => 'CAOL850714HV9',
                'tax_regime' => '621',
                'curp' => 'CAOL850714HDFXRS06',
                'legal_rep_name' => null,
                'legal_rep_rfc' => null,
                'economic_activity' => 'Taller mecánico y venta de refacciones',
                'scian_code' => '81111',
                'employee_count' => 5,
                'email' => 'tallerlfc@hotmail.com',
                'phone' => null,
                'address' => 'Av. Industrial 892 Col. Valle Verde',
                'city' => 'Puebla',
                'state' => 'Puebla',
                'country' => 'MX',
                'postal_code' => '72140',
                'status' => 'active',
                'billing_cycle' => 'monthly',
                'obligations_periodicity' => 'bimestral',
                'compliance_level' => 'low',
                'relationship_started_at' => '2023-09-01',
                'onboarding_completed_at' => '2023-09-12 16:00:00',
                'onboarding_notes' => 'Régimen de incorporación fiscal. Se aproxima al límite de 2M en ingresos.',
                'portal_sat_user' => 'lchavez_taller85',
                'portal_sat_password' => 'T@ller2023lfc!',
                'documents' => [
                    'constancia_situacion_fiscal' => true,
                    'poder_notarial' => false,
                    'identificacion' => true,
                ],
            ],
            [
                'person_type' => 'moral',
                'name' => 'Clínica Médica San Rafael SC',
                'tax_id' => 'CMS010301NX5',
                'tax_regime' => '603',
                'curp' => null,
                'legal_rep_name' => 'Dra. Sofía Ramírez Delgado',
                'legal_rep_rfc' => 'RADS760902MDF',
                'economic_activity' => 'Servicios de atención médica ambulatoria',
                'scian_code' => '62111',
                'employee_count' => 22,
                'email' => 'administracion@clinicasanrafael.com.mx',
                'phone' => null,
                'address' => 'Calle Salud 300 Col. Doctores',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'country' => 'MX',
                'postal_code' => '06720',
                'status' => 'active',
                'billing_cycle' => 'monthly',
                'obligations_periodicity' => 'mensual',
                'compliance_level' => 'high',
                'relationship_started_at' => '2017-11-01',
                'onboarding_completed_at' => '2017-11-15 10:30:00',
                'onboarding_notes' => 'Sociedad civil médica. Exenta de IVA en servicios de salud.',
                'portal_sat_user' => 'clinica_rafaelsc',
                'portal_sat_password' => 'M3d1c@2017!',
                'documents' => [
                    'constancia_situacion_fiscal' => true,
                    'poder_notarial' => true,
                    'identificacion' => true,
                ],
            ],
            [
                'person_type' => 'fisica',
                'name' => 'Gabriela Torres Espinoza',
                'tax_id' => 'TOEG910830QS1',
                'tax_regime' => '626',
                'curp' => 'TOEG910830MDFRRB07',
                'legal_rep_name' => null,
                'legal_rep_rfc' => null,
                'economic_activity' => 'Servicios de consultoría en recursos humanos',
                'scian_code' => '54161',
                'employee_count' => 1,
                'email' => 'gabriela.torres.rh@gmail.com',
                'phone' => null,
                'address' => 'Av. Insurgentes Sur 1602 Piso 3 Col. Crédito Constructor',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'country' => 'MX',
                'postal_code' => '03940',
                'status' => 'inactive',
                'billing_cycle' => 'monthly',
                'obligations_periodicity' => 'mensual',
                'compliance_level' => 'low',
                'relationship_started_at' => '2022-03-01',
                'onboarding_completed_at' => '2022-03-08 13:00:00',
                'onboarding_notes' => 'Cliente inactivo por cambio de residencia al extranjero. Pendiente aviso de suspensión ante SAT.',
                'portal_sat_user' => 'gtorres_rh91',
                'portal_sat_password' => 'R3s1c0@2022!',
                'documents' => [
                    'constancia_situacion_fiscal' => true,
                    'poder_notarial' => false,
                    'identificacion' => true,
                ],
            ],
        ];

        foreach ($clients as $data) {
            Client::create(array_merge($data, ['user_id' => $admin->id]));
        }
    }
}
